# Generate paraphrase_typology_df.csv

In [1]:
import pandas as pd
import os
import re

## Running through all the files and getting the data we need: entities mentions


###### IMPORTANT ADD THE PATH UNTIL SENTENCES DIRECTORY WHEN RUNNING IT

In [15]:
#phase = "val"
#phase = "train"
phase = "test_2016_flickr"

partition_file = "/home/wenjian/Internship/data/flickr30kentities/Multi30k/task1/image_splits/" + phase + ".txt"
output_path = f"/home/wenjian/Internship/data/flickr30kentities/queries_extracted/{phase}_queries.csv"

imageID_list = []
with open(partition_file, 'r') as f:
    l = f.readline()
    while l :
        imageID_list.append(l.split('.')[0])
        l = f.readline()

#Defining regex structure to parse information 
regex = r"\[(.*?)\]"

#Data directory
#directory = 'vgp/flickr30k_entities/annotations/testing_algo'
directory = './annotations/Sentences'
nbr_sentences_file = len(imageID_list)
counter = 0
#Create dictionary to append data and further transform in Dataframe 
dict_df = {'imgId_entityId_entClass':[], 'imgId':[], 'entityId':[], 'entity_content':[], 'entClass':[]}

In [16]:


## Iterating over all files flickr30_entities 
for imgId in imageID_list:
    filename = imgId + ".txt"
    f = open(os.path.join(directory,filename))
    if not counter%100: 
        print(str(counter)+'/' + str(nbr_sentences_file))
    counter+=1
    
    #Get next line
    line = f.readline()
    # While the document still have lines, we will continue to read it
    while line:
        #print(line)

        #Defining dataframe variables 
        entityId = ''
        entity_content = ''
        imgId_entityId_entClass = ''
        entClass = ''

        ### Applying regex in order to find the wanted structures 
        test_str = (line)

        ##Get matches 
        matches = re.finditer(regex, test_str, re.MULTILINE)

        ## Iterate over matches and save information
        for matchNum, match in enumerate(matches, start=1):
            for groupNum in range(0, len(match.groups())):

                groupNum = groupNum + 1
                # get entityId by first splitting the '/EN#255542/people A bearded man' in '/' and later splitting in the '#'. We then get the second memeber of the list
                entityId = match.group(groupNum).split('/')[1].split('#')[1]
                #We split the words after the last '/' in order to catch the class and the content 
                words = match.group(groupNum).split('/')[2].split(' ')
                entClass = words[0]
                #We join all the words minus the class word to find our entity content 
                entity_content = ' '.join(words[1:]) 
                #Creating an unique id for the entry
                imgId_entityId_entClass = imgId +'_' +str(entityId)+ '_' + str(entClass)

                '''
                print(entClass)
                print(entityId)
                print(imgId)
                print(imgId_entityId_entClass)
                print(entity_content)
                '''
                #Adding to dict to further add to the df
                dict_df['imgId_entityId_entClass'].append(imgId_entityId_entClass)
                dict_df['imgId'].append(imgId)
                dict_df['entityId'].append(entityId)
                dict_df['entity_content'].append(entity_content)
                dict_df['entClass'].append(entClass)



        #next iteration
        line = f.readline()


    #print('----------------File ended----------------')

0/1000
100/1000
200/1000
300/1000
400/1000
500/1000
600/1000
700/1000
800/1000
900/1000

In [11]:
# For AMT annotated French sentences

#phase = "val"
#phase = "train"
phase = "test_2016_flickr"

partition_file = "/home/wenjian/Internship/data/flickr30kentities/Multi30k/task1/image_splits/" + phase + ".txt"
output_path = f"/home/wenjian/Internship/data/flickr30kentities/queries_extracted/{phase}_3000_queries_fr.csv"

imageID_list = []  # Although we don't need image id to find the sentence, we still need to add image id into our csv file
with open(partition_file, 'r') as f:
    l = f.readline()
    while l :
        imageID_list.append(l.split('.')[0])
        l = f.readline()

#Defining regex structure to parse information 
regex = r"\[(.*?)\]"

#Data directory
#directory = 'vgp/flickr30k_entities/annotations/testing_algo'


#Create dictionary to append data and further transform in Dataframe 
dict_df = {'imgId_entityId_entClass':[], 'imgId':[], 'entityId':[], 'entity_content':[], 'entClass':[]}
#f = open("/home/wenjian/Internship/data/AmazonMTurk/results_parsed_accepted/public_train_0-2999.fr", "r")
#f = open("/home/wenjian/Internship/data/AmazonMTurk/results_parsed_accepted/public_val.fr", "r")
f = open("/home/wenjian/Internship/data/AmazonMTurk/results_parsed_accepted/public_test.fr", "r")

#Get next line
line = f.readline()
counter = 0
# While the document still have lines, we will continue to read it
while line:
    #print(line)
    # line example: val**0**e** [/EN#568/people un groupe d' hommes] chargent [/EN#569/other du coton] dans [/EN#570/vehicles un camion]
    line = line.split('**')[3]  # To remove flags in AMT task
    imgId = imageID_list[counter]

    #Defining dataframe variables 
    entityId = ''
    entity_content = ''
    imgId_entityId_entClass = ''
    entClass = ''

    ### Applying regex in order to find the wanted structures 
    test_str = (line)

    ##Get matches 
    matches = re.finditer(regex, test_str, re.MULTILINE)

    ## Iterate over matches and save information
    for matchNum, match in enumerate(matches, start=1):
        for groupNum in range(0, len(match.groups())):

            groupNum = groupNum + 1
            # get entityId by first splitting the '/EN#255542/people A bearded man' in '/' and later splitting in the '#'. We then get the second memeber of the list
            entityId = match.group(groupNum).split('/')[1].split('#')[1]
            #We split the words after the last '/' in order to catch the class and the content 
            words = match.group(groupNum).split('/')[2].split(' ')
            entClass = words[0]
            #We join all the words minus the class word to find our entity content 
            entity_content = ' '.join(words[1:]) 
            #Creating an unique id for the entry
            imgId_entityId_entClass = imgId +'_' +str(entityId)+ '_' + str(entClass)

            '''
            print(entClass)
            print(entityId)
            print(imgId)
            print(imgId_entityId_entClass)
            print(entity_content)
            '''
            #Adding to dict to further add to the df
            dict_df['imgId_entityId_entClass'].append(imgId_entityId_entClass)
            dict_df['imgId'].append(imgId)
            dict_df['entityId'].append(entityId)
            dict_df['entity_content'].append(entity_content)
            dict_df['entClass'].append(entClass)



    #next iteration
    line = f.readline()
    counter += 1
    if counter%100 == 0:
        print(f"{counter}/{len(imageID_list)}")
f.close()

100/1000
200/1000
300/1000
400/1000
500/1000
600/1000
700/1000
800/1000
900/1000
1000/1000

## Saving file after getting a dataframe

In [12]:
df = pd.DataFrame(data=dict_df)

In [13]:
df.info() # In the exploration we saw there are spme null string values. we gonna delete it

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3330 entries, 0 to 3329
Data columns (total 5 columns):
imgId_entityId_entClass    3330 non-null object
imgId                      3330 non-null object
entityId                   3330 non-null object
entity_content             3330 non-null object
entClass                   3330 non-null object
dtypes: object(5)
memory usage: 130.2+ KB

## Exclude Null values ('')

In [14]:
df = df[df['entity_content'] != '']

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3311 entries, 0 to 3329
Data columns (total 5 columns):
imgId_entityId_entClass    3311 non-null object
imgId                      3311 non-null object
entityId                   3311 non-null object
entity_content             3311 non-null object
entClass                   3311 non-null object
dtypes: object(5)
memory usage: 155.2+ KB

In [8]:
df

,imgId_entityId_entClass,imgId,entityId,entity_content,entClass
0,1018148011_568_people,1018148011,568,un groupe d' hommes,people
1,1018148011_569_other,1018148011,569,du coton,other
2,1018148011_570_vehicles,1018148011,570,un camion,vehicles
3,1029450589_844_people,1029450589,844,un homme,people
4,1029450589_846_scene,1029450589,846,une chambre verte,scene
5,1029450589_845_other,1029450589,845,un canapé,other
6,1029737941_850_people,1029737941,850,un garçon,people
7,1029737941_853_clothing,1029737941,853,un casque,clothing
8,1029737941_852_bodyparts,1029737941,852,les épaules d' une femme,bodyparts
9,103205630_929_people,103205630,929,deux hommes,people
10,103205630_928_scene,103205630,928,une tente de pêche,scene
11,103205630_931_other,103205630,931,glace,other
12,103205630_932_scene,103205630,932,un lac gelé,scene
13,10350842_988_people,10350842,988,un homme chauve,people
14,10350842_991_clothing,10350842,991,un gilet de sauvetage rouge,clothing
16,1054620089_1389_people,1054620089,1389,une femme,people
17,1054620089_1392_clothing,1054620089,1392,manteau rouge,clothing
18,1054620089_1390_clothing,1054620089,1390,un sac à main bleuté,clothing
19,1054620089_1389_scene,1054620089,1389,origine asiatique,scene
20,1054620089_1394_other,1054620089,1394,une photo,other
21,1056873310_1474_animals,1056873310,1474,un chien brun,animals
22,1056873310_1477_animals,1056873310,1477,le chien noir,animals
23,1072439304_1742_people,1072439304,1742,un jeune garçon,people
24,1072439304_1743_clothing,1072439304,1743,un maillot des giants,clothing
25,1072439304_1745_other,1072439304,1745,une batte de base-ball,other
26,1072439304_1744_scene,1072439304,1744,une balle qui arrive,scene
27,1073444492_1759_people,1073444492,1759,un homme,people
28,1073444492_1763_scene,1073444492,1763,un bureau encombré,scene
29,1073444492_1761_other,1073444492,1761,le téléphone,other
30,1092437557_2227_people,1092437557,2227,une femme souriante,people
...,...,...,...,...,...
3321,821605360_280466_people,821605360,280466,une femme,people
3322,821605360_280470_bodyparts,821605360,280470,une jambe,bodyparts
3323,821605360_280467_scene,821605360,280467,une grande falaise,scene
3324,821605360_280468_scene,821605360,280468,une rivière,scene
3325,8251170369_280875_people,8251170369,280875,une femme brune,people
3326,8251170369_280878_scene,8251170369,280878,le trottoir,scene
3327,8251170369_280876_scene,8251170369,280876,la route,scene
3328,82676249_280929_people,82676249,280929,un groupe de trois amis,people
3329,82676249_280938_scene,82676249,280938,une maison,scene
3330,841397013_281277_people,841397013,281277,deux chinois,people
3331,841397013_281278_other,841397013,281278,un tableau noir,other
3332,8443156_281350_people,8443156,281350,une personne,people
3333,8443156_281354_clothing,8443156,281354,un jean,clothing
3334,8443156_281353_clothing,8443156,281353,un pull rouge,clothing
3335,8443156_281358_other,8443156,281358,l' angle d' un mur,other
3336,860271719_281813_people,860271719,281813,des agriculteurs,people
3337,860271719_281817_scene,860271719,281817,la journée,scene
3338,86120374_281944_other,86120374,281944,un carnaval,other
3339,86120374_281937_people,86120374,281937,un homme,people
3340,86120374_281938_other,86120374,281938,la barbe à papa,other
3341,86131989_282081_people,86131989,282081,un groupe de policiers,people
3343,91875542_283494_people,91875542,283494,une vieille femme aux cheveux blancs,people
3344,91875542_283495_other,91875542,283495,sa caisse enregistreuse,other
3345,91875542_283496_clothing,91875542,283496,ses lunettes,clothing
3346,981727078_284864_people,981727078,284864,deux hommes,people
3347,981727078_284865_scene,981727078,284865,des cabines téléphoniques,scene
3348,991459823_285100_people,991459823,285100,deux femmes,people
3349,991459823_285104_clothing,991459823,285104,rouge,clothing
3350,991459823_285099_people,991459823,285099,un homme,people
3351,991459823_285101_other,991459823,285101,toilettes portables,other

## Exclude entries with no bounding box

In [22]:
import xml.etree.ElementTree as ET
xml_directory = "/home/wenjian/Internship/data/flickr30kentities/annotations/Annotations/"
def have_bounding_box(image_id, object_id): # image_id and object_id are expected to be string
    xml_tree = ET.parse(xml_directory + image_id + '.xml')
    root = xml_tree.getroot()
    for obj in root.findall('object'):
        for name in obj:
            if name.text == object_id:
                if len(obj.findall('bndbox')) >= 1:
                    return True
    return False

In [23]:
have_bounding_box("2679015215", "65727")  # For testing

True

In [24]:
def have_bounding_box_for_dataframe(imgId_entityId_entClass):
    image_id = imgId_entityId_entClass.split("_")[0]
    object_id = imgId_entityId_entClass.split("_")[1]
    return have_bounding_box(image_id, object_id)

In [25]:
df1 = df[df['imgId_entityId_entClass'].apply(lambda x: have_bounding_box_for_dataframe(x))]

In [26]:
df1

,imgId_entityId_entClass,imgId,entityId,entity_content,entClass
0,1007129816_203_people,1007129816,203,The man,people
1,1007129816_207_bodyparts,1007129816,207,pierced ears,bodyparts
2,1007129816_205_clothing,1007129816,205,glasses,clothing
3,1007129816_204_clothing,1007129816,204,an orange hat,clothing
4,1007129816_203_people,1007129816,203,A man,people
5,1007129816_205_clothing,1007129816,205,glasses,clothing
6,1007129816_204_clothing,1007129816,204,a beer can crocheted hat,clothing
7,1007129816_203_people,1007129816,203,A man,people
8,1007129816_207_other,1007129816,207,gauges,other
9,1007129816_205_clothing,1007129816,205,glasses,clothing
10,1007129816_204_clothing,1007129816,204,a Blitz hat,clothing
11,1007129816_203_people,1007129816,203,A man,people
12,1007129816_204_clothing,1007129816,204,an orange hat,clothing
14,1007129816_203_people,1007129816,203,A man,people
15,1007129816_204_clothing,1007129816,204,an orange hat,clothing
16,1007129816_205_clothing,1007129816,205,glasses,clothing
17,1009434119_271_animals,1009434119,271,A black and white dog,animals
18,1009434119_272_scene,1009434119,272,a grassy garden,scene
19,1009434119_273_scene,1009434119,273,a white fence,scene
20,1009434119_271_animals,1009434119,271,A Boston Terrier,animals
21,1009434119_272_scene,1009434119,272,lush green grass,scene
22,1009434119_273_scene,1009434119,273,a white fence,scene
23,1009434119_271_animals,1009434119,271,A black and white dog,animals
24,1009434119_272_scene,1009434119,272,the grass,scene
25,1009434119_271_animals,1009434119,271,A dog,animals
26,1009434119_272_scene,1009434119,272,the green grass,scene
27,1009434119_273_scene,1009434119,273,a wooden fence,scene
28,1009434119_271_animals,1009434119,271,A Boston terrier,animals
29,1009434119_272_scene,1009434119,272,the grass,scene
30,101362133_432_people,101362133,432,A young female student,people
...,...,...,...,...,...
17654,95758790_284185_people,95758790,284185,A child,people
17655,95758790_284182_people,95758790,284182,his friend,people
17656,95758790_284184_other,95758790,284184,the tree,other
17657,97233789_284614_people,97233789,284614,A man,people
17659,97233789_284617_clothing,97233789,284617,the tan coat,clothing
17660,97233789_284616_other,97233789,284616,a casino slot machine,other
17661,97233789_284614_people,97233789,284614,older man,people
17662,97233789_284616_other,97233789,284616,a slot machine,other
17664,97233789_284614_people,97233789,284614,An older man,people
17665,97233789_284616_other,97233789,284616,a video arcade game,other
17666,97233789_284614_people,97233789,284614,An old man,people
17667,97233789_284616_other,97233789,284616,a game,other
17669,97233789_284614_people,97233789,284614,Man,people
17670,97233789_284616_other,97233789,284616,slots,other
17672,97234558_284619_people,97234558,284619,A young girl,people
17673,97234558_284621_scene,97234558,284621,the water,scene
17674,97234558_284623_other,97234558,284623,safety floatation devices,other
17675,97234558_284627_bodyparts,97234558,284627,her arms,bodyparts
17676,97234558_284619_people,97234558,284619,The baby,people
17677,97234558_284620_clothing,97234558,284620,the gold,clothing
17678,97234558_284620_scene,97234558,284620,sandy-colored beach,scene
17679,97234558_284621_scene,97234558,284621,water,scene
17681,97234558_284619_people,97234558,284619,A girl,people
17682,97234558_284620_scene,97234558,284620,the shore of a beach,scene
17683,97234558_284622_scene,97234558,284622,a mountain,scene
17685,97234558_284619_people,97234558,284619,Little girl,people
17686,97234558_284628_clothing,97234558,284628,arm floaties,clothing
17687,97234558_284620_other,97234558,284620,the coast line,other
17688,97234558_284619_people,97234558,284619,A child,people
17689,97234558_284621_scene,97234558,284621,the ocean,scene

413627 rows × 5 columns

In [27]:

df1.to_csv(output_path)

## Random tests

In [ ]:
# Create a dataframe
import numpy as np
raw_data = {'first_name': ['Jason', 'Molly', np.nan, np.nan, np.nan], 
        'nationality': ['USA', 'USA', 'France', 'UK', 'UK'], 
        'age': [42, 52, 36, 24, 70]}
df0 = pd.DataFrame(raw_data, columns = ['first_name', 'nationality', 'age'])
df0

In [ ]:
df0[df0['nationality'] == 'USA']

In [ ]:
def myFunc(row):
    n = row['nationality']
    a = row['age']
    if n=="USA" and 40<a<50:
        return True
    else:
        return False

In [ ]:
df0.apply(myFunc)

In [ ]:
import xml.etree.ElementTree as ET
xml_directory = "/home/wenjian/Internship/data/flickr30kentities/annotations/Annotations/"
tree = ET.parse(xml_directory + '2679015215.xml')
root = tree.getroot()
for t in root.findall("object"):
    print(len(t.findall("bndbox")))

In [ ]:
a = 45
40<a<50